const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
const DECREASE_PRODUCT_FROM_BASKET = 'DECREASE_PRODUCT_FROM_BASKET';
const REMOVE_ALL_PRODUCTS_FROM_BASKET = 'REMOVE_ALL_PRODUCTS_FROM_BASKET';
const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET';

export {
  ADD_PRODUCT_TO_BASKET,
  DECREASE_PRODUCT_FROM_BASKET,
  REMOVE_ALL_PRODUCTS_FROM_BASKET,
  REMOVE_PRODUCT_FROM_BASKET
};
